# Generated by Django 4.1.7 on 2023-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_transaccion', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('compra', 'Compra'), ('transferencia', 'Transferencia'), ('apertura', 'Apertura'), ('cancelacion', 'Cancelacion')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('establecimiento', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
    ]
